spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update # use 'update' to make persistent, or 'create' for fresh data
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/cvs-to-database;
    driverClassName: org.h2.Driver
    username: sa
    password: