spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/cvs-to-database;
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true